import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // General
    'app.name': 'Gateway',
    'skip': 'Skip',
    'continue': 'Continue',
    'retry': 'Retry',
    'done': 'Done',
    'cancel': 'Cancel',
    'yes': 'Yes',
    'no': 'No',
    
    // Login
    'login.title': 'Heights',
    'login.subtitle': 'Choose how you want to connect',
    'login.method.title': 'Select Login Method',
    'login.method.local': 'Login with Local',
    'login.method.local.description': 'Connect directly to your local network',
    'login.method.cloud': 'Login with Cloud',
    'login.method.cloud.description': 'Access remotely through cloud services',
    'login.form.title': 'Login Credentials',
    'login.form.username': 'Username',
    'login.form.email': 'Email Address',
    'login.form.password': 'Password',
    'login.terms.agree': 'I agree to the',
    'login.terms.link': 'Terms & Agreements',
    'login.terms.required': 'You must agree to the terms to continue',
    'login.error.method': 'Please select a login method',
    'login.error.username': 'Please enter your username',
    'login.error.email': 'Please enter your email address',
    'login.error.email.invalid': 'Please enter a valid email address',
    'login.error.password': 'Please enter your password',
    'login.error.password.short': 'Password must be at least 6 characters',
    'login.button': 'Continue',
    'login.footer': 'Secure connection • Privacy protected',
    
    // Welcome
    'welcome.title': 'Welcome to Heights!',
    'welcome.message': "Hi! I'm Janus, your Heights assistant. I'll help you set up your devices. What would you like to set up?",
    'welcome.setup.gateway': 'Set up Gateway',
    'welcome.setup.extender': 'Add Extender',
    'welcome.quick.setup': 'Quick Setup',
    'welcome.quick.desc': 'Already know the steps? Pre-fill and auto-complete',

    // Quick Setup
    'quick.title': 'Quick Setup',
    'quick.subtitle': 'Pre-fill details and let us handle the rest',
    'quick.form.location': 'Location',
    'quick.form.location.placeholder': 'e.g. Home, Office, Factory',
    'quick.form.ssid': 'Wi-Fi Name (SSID)',
    'quick.form.ssid.placeholder': 'e.g. MyHome-WiFi',
    'quick.form.password': 'Wi-Fi Password',
    'quick.form.password.placeholder': 'Minimum 8 characters',
    'quick.form.password.hint': 'At least 8 characters. Use letters, numbers and symbols for a strong password.',
    'quick.start': 'Start Automatic Setup',
    'quick.running.start': "Great! I have everything I need. Starting automatic setup now — no need to tap anything.",
    'quick.running.qr': 'QR code scanned and device identified.',
    'quick.running.ocr': 'Device label captured and credentials read.',
    'quick.running.wan': 'WAN configuration pushed to gateway.',
    'quick.running.wifi': 'Wi-Fi personalized to "{ssid}" and settings applied.',
    'quick.step.qr': 'Scan QR code',
    'quick.step.ocr': 'Capture device label',
    'quick.step.wan': 'Push WAN config',
    'quick.step.wifi': 'Personalize Wi-Fi',
    'quick.step.apply': 'Apply & connect',
    'quick.step.bt': 'Bluetooth scan',
    'quick.step.link': 'Link to gateway',
    'quick.choose.title': 'What would you like to set up?',
    'quick.choose.gateway': 'Gateway',
    'quick.choose.gateway.desc': 'Set up a new gateway device',
    'quick.choose.extender': 'Extender',
    'quick.choose.extender.desc': 'Add an extender to your network',
    'quick.auto.label.location': 'Location',
    'quick.auto.label.ssid': 'Wi-Fi Name',
    'quick.auto.label.password': 'Password',
    'quick.auto.desc': 'Auto-generated — you can customize below',
    'quick.advanced': 'Advanced options',
    'quick.advanced.hide': 'Hide advanced options',
    'quick.running.bt': 'Bluetooth scan complete — extender found.',
    'quick.running.link': 'Extender linked to gateway successfully.',
    'quick.running.extender.wifi': 'Wi-Fi settings pushed to extender.',
    'quick.done.message.gateway': 'Your gateway is set up and ready!',
    'quick.done.message.extender': 'Your extender is set up and ready!',
    'quick.done.finish': 'Finish',
    'quick.done.repair': 'Something went wrong — retry',
    'quick.done.repeat.extender': 'Add another Extender',
    'quick.extender.select': 'Select your gateway',
    'quick.extender.nogateways': 'No gateways found. Set up a gateway first.',
    'quick.extender.add.gateway': 'Add a gateway',
    'quick.extender.bt.tab': 'Bluetooth',
    'quick.extender.manual.tab': 'Manual entry',
    'quick.extender.bt.scanning': 'Scanning for nearby extenders…',
    'quick.extender.manual.serial.placeholder': 'Serial number',
    'quick.extender.manual.model.placeholder': 'Model name',

    // Gateway Flow
    'gateway.step1.title': 'Connect Your Gateway',
    'gateway.step1.message': 'Please ensure your Gateway is powered on and the WAN Ethernet cable is connected.',
    'gateway.step1.instruction1': 'Power on your Gateway device',
    'gateway.step1.instruction2': 'Connect WAN Ethernet cable',
    'gateway.step1.instruction3': 'Wait for the LED to turn solid blue',
    'gateway.step1.ready': "I've connected it",
    
    // Gateway Onboarding - Location
    'gateway.location.title': 'Set Location',
    'gateway.location.message': 'Where are you setting up this Gateway?',
    'gateway.location.myhome.suffix': '\'s Home',
    'gateway.location.floor1': '1st Floor',
    'gateway.location.floor2': '2nd Floor',
    'gateway.location.floor3': '3rd Floor',
    'gateway.location.custom': 'Custom Location',
    'gateway.location.custom.placeholder': 'Enter location name',
    'gateway.location.continue': 'Continue',
    
    // Gateway WAN Configuration
    'gateway.wan.title': 'Configure WAN',
    'gateway.wan.message': 'How does your Gateway connect to the internet?',
    'gateway.wan.recommended': 'Recommended',
    'gateway.wan.optional': 'Optional',
    'gateway.wan.dhcp.title': 'DHCP (Automatic)',
    'gateway.wan.dhcp.desc': 'Automatically get IP address from your ISP',
    'gateway.wan.pppoe.title': 'PPPoE',
    'gateway.wan.pppoe.desc': 'Connect using username and password from ISP',
    'gateway.wan.pppoe.howenter': 'How would you like to enter your PPPoE credentials?',
    'gateway.wan.pppoe.scan': 'Scan ISP Document',
    'gateway.wan.pppoe.scan.desc': 'Use camera to auto-read credentials from your ISP letter',
    'gateway.wan.pppoe.enter': 'Enter Manually',
    'gateway.wan.pppoe.enter.desc': 'Type your PPPoE username and password',
    'gateway.wan.pppoe.config': 'PPPoE Configuration',
    'gateway.wan.pppoe.username': 'Username',
    'gateway.wan.pppoe.username.placeholder': 'Enter PPPoE username',
    'gateway.wan.pppoe.password': 'Password',
    'gateway.wan.pppoe.password.placeholder': 'Enter PPPoE password',
    'gateway.wan.static.title': 'Static IP',
    'gateway.wan.static.desc': 'Manually configure IP address settings',
    'gateway.wan.static.config': 'Static IP Configuration',
    'gateway.wan.static.ip': 'IP Address',
    'gateway.wan.static.subnet': 'Subnet Mask',
    'gateway.wan.static.gateway': 'Default Gateway',
    'gateway.wan.static.dns1': 'Primary DNS',
    'gateway.wan.static.dns2': 'Secondary DNS',
    
    // Gateway Selection for Extender
    'gateway.select.title': 'Select Gateway',
    'gateway.select.message': 'Which Gateway do you want to add the extender to?',
    'gateway.select.nogateways': 'No Gateways found. You need to set up a Gateway first before adding extenders.',
    'gateway.select.required': 'Gateway Required',
    'gateway.select.required.desc': 'Extenders need to connect to an existing Gateway. Please set up your Gateway first.',
    'gateway.select.setup.first': 'Set up your Gateway to get started',
    'gateway.select.add.another': 'Add Another Gateway',
    
    'gateway.step2.title': 'Connecting to Cloud',
    'gateway.step2.message': 'Your Gateway is connecting to the cloud...',
    'gateway.step2.registering': 'Registering device...',
    'gateway.step2.claiming': 'Claiming to location...',
    'gateway.step2.configuring': 'Configuring settings...',
    'gateway.step2.starting': 'Starting onboarding network...',
    
    'gateway.success.title': 'Gateway Online! 🎉',
    'gateway.success.message': 'Your Gateway is now online and ready. The onboarding network is active for adding extenders.',
    'gateway.success.ssid': 'Onboarding SSID',
    'gateway.success.status': 'Status',
    'gateway.success.location': 'Location',
    'gateway.success.add.extender': 'Add Extender',
    'gateway.success.finish': 'Finish Setup',

    // New Gateway Provisioning Flow
    'gateway.qr.title': 'Scan QR Code',
    'gateway.qr.message': "Let me scan your Gateway's QR code to get its provisioning credentials.",
    'gateway.qr.detected': 'QR code detected! Reading device credentials...',
    'gateway.qr.connecting': 'Connecting to your Gateway provisioning network...',
    'gateway.qr.connected': 'Connected! Retrieving configuration...',
    'gateway.qr.connected.label': 'Connected to provisioning network',
    'gateway.qr.connecting.label': 'Connecting to provisioning network...',

    'gateway.ocr.title': 'Capture ISP Credentials',
    'gateway.ocr.message': 'I can scan your ISP welcome letter or modem label to automatically read your PPPoE credentials.',
    'gateway.ocr.capture.button': 'Scan Document',
    'gateway.ocr.capture.desc': 'Point camera at your ISP letter or modem label',
    'gateway.ocr.capture.start': 'Start scanning',
    'gateway.ocr.extracting': 'Extracting credentials from image...',
    'gateway.ocr.extracted': 'Credentials extracted successfully!',
    'gateway.ocr.confirm': 'Confirm credentials',
    'gateway.ocr.review.title': 'Review Extracted Credentials',
    'gateway.ocr.review.type': 'Connection Type',
    'gateway.ocr.review.username': 'Username',
    'gateway.ocr.review.password': 'Password',
    'gateway.ocr.review.confirm': 'Confirm & Apply',
    'gateway.ocr.review.edit': 'Edit',
    'gateway.ocr.edit.title': 'Edit Credentials',
    'gateway.ocr.edit.save': 'Save Changes',
    'gateway.ocr.skip': 'Enter Manually',
    'gateway.ocr.skip.desc': 'Type your credentials manually instead',

    'gateway.wanpush.title': 'Pushing WAN Config',
    'gateway.wanpush.message': 'Pushing your WAN configuration to the Gateway...',
    'gateway.wanpush.step1': 'Connecting to Gateway',
    'gateway.wanpush.step2': 'Sending WAN credentials',
    'gateway.wanpush.step3': 'Applying configuration',
    'gateway.wanpush.step4': 'Verifying internet connection',
    'gateway.wanpush.success': 'WAN configuration applied successfully!',
    'gateway.wanpush.internet.connected': 'Internet Connected',
    'gateway.wanpush.internet.desc': 'Your Gateway is now connected to the internet',

    'gateway.wifi.title': 'Personalize Your WiFi',
    'gateway.wifi.location.message': "Where are you setting up this Gateway? This helps us suggest the best WiFi name for your location.",
    'gateway.wifi.location.home': 'Home',
    'gateway.wifi.location.office': 'Office',
    'gateway.wifi.location.factory': 'Factory',
    'gateway.wifi.location.shop': 'Shop / Store',
    'gateway.wifi.location.custom': 'Custom Location',
    'gateway.wifi.location.custom.placeholder': 'Enter location name (e.g. My Company)',
    'gateway.wifi.message': "Now let's set up your WiFi network name and password.",
    'gateway.wifi.ssid.label': 'Network Name (SSID)',
    'gateway.wifi.ssid.placeholder': 'Enter network name',
    'gateway.wifi.ssid.suggestions': 'Suggestions',
    'gateway.wifi.password.label': 'WiFi Password',
    'gateway.wifi.password.placeholder': 'Enter password (min. 8 characters)',
    'gateway.wifi.password.weak': 'Weak',
    'gateway.wifi.password.medium': 'Medium',
    'gateway.wifi.password.strong': 'Strong',
    'gateway.wifi.preview': 'Network Preview',

    'gateway.apply.title': 'Applying Configuration',
    'gateway.apply.message': 'Applying your WiFi settings to the Gateway...',
    'gateway.apply.step1': 'Saving WiFi settings',
    'gateway.apply.step2': 'Restarting wireless radio',
    'gateway.apply.step3': 'Switching to your new network',
    'gateway.apply.step4': 'Finalizing setup',
    'gateway.apply.success': 'Configuration applied successfully!',
    'gateway.apply.switching': 'Switching networks...',
    'gateway.apply.switched': 'Connected to your new network!',
    'gateway.apply.new.network': 'Your new WiFi network is ready',

    // Extender Flow
    'extender.step1.title': 'Add Extender',
    'extender.step1.message': 'To add an extender, I\'ll scan for nearby devices via Bluetooth. If your Extender supports Bluetooth, power it on and it will appear in the list below. You can also scan the QR code on your device or enter the serial number manually.',
    'extender.step1.bluetooth.scanning': 'Bluetooth Scan',
    'extender.step1.bluetooth.searching': 'Searching for nearby devices...',
    'extender.step1.bluetooth.none': 'No nearby devices found',
    'extender.step1.bluetooth.rescan': 'Rescan',
    'extender.step1.selected': 'Device selected',
    'extender.step1.or': 'or use another method',
    'extender.step1.scan': 'Scan QR Code',
    'extender.step1.manual': 'Enter Serial Number',
    
    'extender.step2.title': 'Enter Serial Number',
    'extender.step2.message': 'Please enter the serial number found on the back of your extender.',
    'extender.step2.placeholder': 'e.g., EXT-1234-5678-90AB',
    'extender.step2.submit': 'Continue',
    'extender.step2.invalid': 'Please enter a valid serial number',
    
    'extender.step3.title': 'Authorizing Device',
    'extender.step3.message': 'Adding extender to your network...',
    'extender.step3.registering': 'Registering extender...',
    'extender.step3.binding': 'Binding to location...',
    'extender.step3.whitelisting': 'Updating MAC whitelist...',
    'extender.step3.authorized': 'Extender authorized!',
    
    'extender.room.title': 'Set Room Location',
    'extender.room.message': 'In which room will this extender be placed?',
    'extender.room.main.location': 'Main Location',
    'extender.room.living': 'Living Room',
    'extender.room.bedroom': 'Bedroom',
    'extender.room.kitchen': 'Kitchen',
    'extender.room.bathroom': 'Bathroom',
    'extender.room.study': 'Study Room',
    'extender.room.garage': 'Garage',
    'extender.room.custom': 'Custom Room',
    'extender.room.custom.placeholder': 'Enter room name',
    'extender.room.continue': 'Continue',

    'extender.wifi.title': 'Set Up Extender WiFi',
    'extender.wifi.message': "Let's configure the WiFi network for your extender.",
    'extender.poweron.title': 'Prepare Your Extender',
    'extender.poweron.message': "Let's get started! Please follow these steps to set up your extender.",
    'extender.poweron.instruction1': 'Place the extender in your desired location',
    'extender.poweron.instruction2': 'Connect the power adapter and plug it in',
    'extender.poweron.instruction3': 'Wait for the LED to turn solid (about 30-60 seconds)',
    'extender.poweron.confirm': 'Extender is Ready',
    
    'extender.step4.title': 'Power On Extender',
    'extender.step4.message': 'Your extender is now authorized. Please power it on to complete the setup.',
    'extender.step4.instruction1': 'Place the extender in the desired location',
    'extender.step4.instruction2': 'Power on the extender',
    'extender.step4.instruction3': 'Wait for connection (may take 1-2 minutes)',
    'extender.step4.ready': 'Extender is powered on',
    
    'extender.step5.title': 'Connecting Extender',
    'extender.step5.message': 'The extender is connecting to your network...',
    'extender.step5.scanning': 'Scanning for setup network...',
    'extender.step5.authenticating': 'Authenticating with Gateway...',
    'extender.step5.connecting': 'Connecting to cloud...',
    'extender.step5.finalizing': 'Applying final configuration...',
    
    'extender.success.title': 'Extender Connected! 🎉',
    'extender.success.message': 'Your extender is now online and extending your network coverage.',
    'extender.success.device': 'Device',
    'extender.success.signal': 'Signal to Gateway',
    'extender.success.coverage': 'Coverage Area',
    'extender.success.add.another': 'Add Another Extender',
    'extender.success.finish': 'Finish Setup',
    
    'extender.error.not.whitelisted': 'Connection rejected - unauthorized device',
    'extender.error.no.network': 'Setup network not found',
    'extender.error.timeout': 'Connection timeout - please try again',
    
    // Device Detection (Legacy - kept for compatibility)
    'detect.searching': "Great! I'm scanning for your Wi-Fi router...",
    'detect.found': "Perfect! I found your device:",
    'detect.confirm': "Is this your router?",
    'detect.not.mine': "That's not mine",
    'detect.correct': "Yes, that's it!",
    
    // Setup (Legacy - kept for compatibility)
    'setup.start': 'Awesome! Let me configure your network...',
    'setup.connecting': 'Connecting to your router...',
    'setup.configuring': 'Optimizing settings...',
    'setup.securing': 'Securing your network...',
    'setup.finalizing': 'Finishing up...',
    
    // Success (Legacy - kept for compatibility)
    'success.title': 'All set! 🎉',
    'success.message': 'Your Gateway network is now active and optimized. You can manage your settings anytime from the dashboard.',
    'success.network.name': 'Network Name',
    'success.devices': 'Connected Devices',
    'success.signal': 'Signal Strength',
    'success.go.dashboard': 'Go to Dashboard',
    
    // Error
    'error.title': 'Oops! Something went wrong',
    'error.connection': "I couldn't connect to the router. This could be due to:",
    'error.reason.power': 'Router is not powered on',
    'error.reason.distance': 'Device is too far from router',
    'error.reason.network': 'Network interference',
    'error.solutions': 'What would you like to do?',
    'error.retry.setup': 'Try Again',
    'error.manual.setup': 'Manual Setup',
    'error.contact.support': 'Contact Support',
    
    // Device Info
    'device.model': 'Model',
    'device.signal': 'Signal',
    'device.status': 'Status',
    'device.status.online': 'Online',
    'device.status.offline': 'Offline',
    
    // Accessibility
    'a11y.typing': 'Assistant is typing',
    'a11y.message.assistant': 'Assistant message',
    'a11y.message.user': 'Your message',
    'a11y.theme.toggle': 'Toggle theme',
    'a11y.language.select': 'Select language',
    'a11y.progress': 'Setup progress',
  },
  es: {
    // General
    'app.name': 'Gateway',
    'skip': 'Omitir',
    'continue': 'Continuar',
    'retry': 'Reintentar',
    'done': 'Hecho',
    'cancel': 'Cancelar',
    'yes': 'Sí',
    'no': 'No',
    
    // Login
    'login.title': 'Heights',
    'login.subtitle': 'Elige cómo quieres conectarte',
    'login.method.title': 'Selecciona el método de inicio de sesión',
    'login.method.local': 'Iniciar sesión con Local',
    'login.method.local.description': 'Conéctate directamente a tu red local',
    'login.method.cloud': 'Iniciar sesión con Cloud',
    'login.method.cloud.description': 'Accede de forma remota a través de servicios en la nube',
    'login.form.title': 'Credenciales de inicio de sesión',
    'login.form.username': 'Nombre de usuario',
    'login.form.email': 'Dirección de correo electrónico',
    'login.form.password': 'Contraseña',
    'login.terms.agree': 'Acepto los',
    'login.terms.link': 'Términos y Acuerdos',
    'login.terms.required': 'Debes aceptar los términos para continuar',
    'login.error.method': 'Por favor, selecciona un método de inicio de sesión',
    'login.error.username': 'Por favor, ingresa tu nombre de usuario',
    'login.error.email': 'Por favor, ingresa tu dirección de correo electrónico',
    'login.error.email.invalid': 'Por favor, ingresa una dirección de correo electrónico válida',
    'login.error.password': 'Por favor, ingresa tu contraseña',
    'login.error.password.short': 'La contraseña debe tener al menos 6 caracteres',
    'login.button': 'Continuar',
    'login.footer': 'Conexión segura • Protección de privacidad',
    
    // Welcome
    'welcome.title': 'Bienvenido a Heights!',
    'welcome.message': "¡Hola! Soy Janus, tu asistente de Heights. Te ayudaré a configurar tus dispositivos. ¿Qué te gustaría configurar?",
    'welcome.setup.gateway': 'Configurar Gateway',
    'welcome.setup.extender': 'Agregar Extensor',
    'welcome.quick.setup': 'Configuración Rápida',
    'welcome.quick.desc': '¿Ya conoces los pasos? Rellena y autocompletamos',

    // Quick Setup
    'quick.title': 'Configuración Rápida',
    'quick.subtitle': 'Rellena los datos y nosotros hacemos el resto',
    'quick.form.location': 'Ubicación',
    'quick.form.location.placeholder': 'ej. Casa, Oficina, Fábrica',
    'quick.form.ssid': 'Nombre de Wi-Fi (SSID)',
    'quick.form.ssid.placeholder': 'ej. MiCasa-WiFi',
    'quick.form.password': 'Contraseña Wi-Fi',
    'quick.form.password.placeholder': 'Mínimo 8 caracteres',
    'quick.form.password.hint': 'Al menos 8 caracteres. Usa letras, números y símbolos para mayor seguridad.',
    'quick.start': 'Iniciar Configuración Automática',
    'quick.running.start': '¡Perfecto! Tengo todo lo necesario. Iniciando configuración automática — no necesitas tocar nada.',
    'quick.running.qr': 'Código QR escaneado y dispositivo identificado.',
    'quick.running.ocr': 'Etiqueta del dispositivo capturada y credenciales leídas.',
    'quick.running.wan': 'Configuración WAN enviada al gateway.',
    'quick.running.wifi': 'Wi-Fi personalizado a "{ssid}" y configuración aplicada.',
    'quick.step.qr': 'Escanear código QR',
    'quick.step.ocr': 'Capturar etiqueta del dispositivo',
    'quick.step.wan': 'Enviar config WAN',
    'quick.step.wifi': 'Personalizar Wi-Fi',
    'quick.step.apply': 'Aplicar y conectar',
    'quick.step.bt': 'Escaneo Bluetooth',
    'quick.step.link': 'Vincular al gateway',
    'quick.choose.title': '¿Qué deseas configurar?',
    'quick.choose.gateway': 'Gateway',
    'quick.choose.gateway.desc': 'Configurar un nuevo dispositivo gateway',
    'quick.choose.extender': 'Extender',
    'quick.choose.extender.desc': 'Añadir un extender a tu red',
    'quick.auto.label.location': 'Ubicación',
    'quick.auto.label.ssid': 'Nombre Wi-Fi',
    'quick.auto.label.password': 'Contraseña',
    'quick.auto.desc': 'Generado automáticamente — puedes personalizar abajo',
    'quick.advanced': 'Opciones avanzadas',
    'quick.advanced.hide': 'Ocultar opciones avanzadas',
    'quick.running.bt': 'Escaneo Bluetooth completo — extender encontrado.',
    'quick.running.link': 'Extender vinculado al gateway con éxito.',
    'quick.running.extender.wifi': 'Configuración Wi-Fi enviada al extender.',
    'quick.done.message.gateway': '¡Tu gateway está configurado y listo!',
    'quick.done.message.extender': '¡Tu extender está configurado y listo!',
    'quick.done.finish': 'Finalizar',
    'quick.done.repair': 'Algo salió mal — reintentar',
    'quick.done.repeat.extender': 'Añadir otro Extender',
    'quick.extender.select': 'Selecciona tu gateway',
    'quick.extender.nogateways': 'No se encontraron gateways. Configura uno primero.',
    'quick.extender.add.gateway': 'Añadir un gateway',
    'quick.extender.bt.tab': 'Bluetooth',
    'quick.extender.manual.tab': 'Entrada manual',
    'quick.extender.bt.scanning': 'Buscando extenders cercanos…',
    'quick.extender.manual.serial.placeholder': 'Número de serie',
    'quick.extender.manual.model.placeholder': 'Nombre del modelo',

    // Gateway Flow
    'gateway.step1.title': 'Conecta tu Gateway',
    'gateway.step1.message': 'Asegúrate de que tu Gateway esté encendido y el cable Ethernet WAN esté conectado.',
    'gateway.step1.instruction1': 'Enciende tu dispositivo Gateway',
    'gateway.step1.instruction2': 'Conecta el cable Ethernet WAN',
    'gateway.step1.instruction3': 'Espera a que el LED se ponga azul sólido',
    'gateway.step1.ready': 'Ya lo conecté',
    
    // Gateway Onboarding - Location
    'gateway.location.title': 'Establecer Ubicación',
    'gateway.location.message': '¿Dónde estás configurando este Gateway?',
    'gateway.location.myhome.suffix': '\'s Home',
    'gateway.location.floor1': '1er Piso',
    'gateway.location.floor2': '2do Piso',
    'gateway.location.floor3': '3er Piso',
    'gateway.location.custom': 'Ubicación Personalizada',
    'gateway.location.custom.placeholder': 'Ingresa el nombre de la ubicación',
    'gateway.location.continue': 'Continuar',
    
    // Gateway WAN Configuration
    'gateway.wan.title': 'Configurar WAN',
    'gateway.wan.message': '¿Cómo se conecta tu Gateway a Internet?',
    'gateway.wan.recommended': 'Recomendado',
    'gateway.wan.optional': 'Opcional',
    'gateway.wan.dhcp.title': 'DHCP (Automático)',
    'gateway.wan.dhcp.desc': 'Obtener automáticamente la dirección IP de tu ISP',
    'gateway.wan.pppoe.title': 'PPPoE',
    'gateway.wan.pppoe.desc': 'Conectar usando el nombre de usuario y la contraseña de tu ISP',
    'gateway.wan.pppoe.howenter': '¿Cómo deseas ingresar tus credenciales PPPoE?',
    'gateway.wan.pppoe.scan': 'Escanear Documento ISP',
    'gateway.wan.pppoe.scan.desc': 'Usa la cámara para leer automáticamente las credenciales de tu carta ISP',
    'gateway.wan.pppoe.enter': 'Ingresar Manualmente',
    'gateway.wan.pppoe.enter.desc': 'Escribe tu usuario y contraseña PPPoE',
    'gateway.wan.pppoe.config': 'Configuración PPPoE',
    'gateway.wan.pppoe.username': 'Nombre de usuario',
    'gateway.wan.pppoe.username.placeholder': 'Ingresa el nombre de usuario PPPoE',
    'gateway.wan.pppoe.password': 'Contraseña',
    'gateway.wan.pppoe.password.placeholder': 'Ingresa la contraseña PPPoE',
    'gateway.wan.static.title': 'IP Estática',
    'gateway.wan.static.desc': 'Configurar manualmente la configuración de la dirección IP',
    'gateway.wan.static.config': 'Configuración IP Estática',
    'gateway.wan.static.ip': 'Dirección IP',
    'gateway.wan.static.subnet': 'Máscara de subred',
    'gateway.wan.static.gateway': 'Puerta de enlace predeterminada',
    'gateway.wan.static.dns1': 'DNS Primario',
    'gateway.wan.static.dns2': 'DNS Secundario',
    
    // Gateway Selection for Extender
    'gateway.select.title': 'Seleccionar Gateway',
    'gateway.select.message': '¿A qué Gateway quieres agregar el extensor?',
    'gateway.select.nogateways': 'No se encontraron Gateways. Necesitas configurar un Gateway primero antes de agregar extensores.',
    'gateway.select.required': 'Gateway Requerido',
    'gateway.select.required.desc': 'Los extensores necesitan conectarse a un Gateway existente. Por favor, configura tu Gateway primero.',
    'gateway.select.setup.first': 'Configura tu Gateway para comenzar',
    'gateway.select.add.another': 'Agregar Otro Gateway',
    
    'gateway.step2.title': 'Conectando a la Nube',
    'gateway.step2.message': 'Tu Gateway se está conectando a la nube...',
    'gateway.step2.registering': 'Registrando dispositivo...',
    'gateway.step2.claiming': 'Asignando a ubicación...',
    'gateway.step2.configuring': 'Configurando ajustes...',
    'gateway.step2.starting': 'Iniciando red de configuración...',
    
    'gateway.success.title': '¡Gateway En Línea! 🎉',
    'gateway.success.message': 'Tu Gateway ya está en línea y listo. La red de configuración está activa para agregar extensores.',
    'gateway.success.ssid': 'SSID de Configuración',
    'gateway.success.status': 'Estado',
    'gateway.success.location': 'Ubicación',
    'gateway.success.add.extender': 'Agregar Extensor',
    'gateway.success.finish': 'Finalizar Configuración',

    // New Gateway Provisioning Flow
    'gateway.qr.title': 'Escanear Código QR',
    'gateway.qr.message': 'Déjame escanear el código QR de tu Gateway para obtener sus credenciales de aprovisionamiento.',
    'gateway.qr.detected': '¡Código QR detectado! Leyendo credenciales del dispositivo...',
    'gateway.qr.connecting': 'Conectando a la red de aprovisionamiento de tu Gateway...',
    'gateway.qr.connected': '¡Conectado! Recuperando configuración...',
    'gateway.qr.connected.label': 'Conectado a la red de aprovisionamiento',
    'gateway.qr.connecting.label': 'Conectando a la red de aprovisionamiento...',

    'gateway.ocr.title': 'Capturar Credenciales ISP',
    'gateway.ocr.message': 'Puedo escanear tu carta de bienvenida del ISP o la etiqueta del módem para leer automáticamente tus credenciales PPPoE.',
    'gateway.ocr.capture.button': 'Escanear Documento',
    'gateway.ocr.capture.desc': 'Apunta la cámara a tu carta del ISP o etiqueta del módem',
    'gateway.ocr.capture.start': 'Iniciar escaneo',
    'gateway.ocr.extracting': 'Extrayendo credenciales de la imagen...',
    'gateway.ocr.extracted': '¡Credenciales extraídas exitosamente!',
    'gateway.ocr.confirm': 'Confirmar credenciales',
    'gateway.ocr.review.title': 'Revisar Credenciales Extraídas',
    'gateway.ocr.review.type': 'Tipo de Conexión',
    'gateway.ocr.review.username': 'Usuario',
    'gateway.ocr.review.password': 'Contraseña',
    'gateway.ocr.review.confirm': 'Confirmar y Aplicar',
    'gateway.ocr.review.edit': 'Editar',
    'gateway.ocr.edit.title': 'Editar Credenciales',
    'gateway.ocr.edit.save': 'Guardar Cambios',
    'gateway.ocr.skip': 'Ingresar Manualmente',
    'gateway.ocr.skip.desc': 'Escribe tus credenciales manualmente en su lugar',

    'gateway.wanpush.title': 'Enviando Configuración WAN',
    'gateway.wanpush.message': 'Enviando tu configuración WAN al Gateway...',
    'gateway.wanpush.step1': 'Conectando al Gateway',
    'gateway.wanpush.step2': 'Enviando credenciales WAN',
    'gateway.wanpush.step3': 'Aplicando configuración',
    'gateway.wanpush.step4': 'Verificando conexión a internet',
    'gateway.wanpush.success': '¡Configuración WAN aplicada exitosamente!',
    'gateway.wanpush.internet.connected': 'Internet Conectado',
    'gateway.wanpush.internet.desc': 'Tu Gateway ahora está conectado a internet',

    'gateway.wifi.title': 'Personaliza tu WiFi',
    'gateway.wifi.location.message': '¿Dónde estás configurando este Gateway? Esto nos ayuda a sugerir el mejor nombre de WiFi para tu ubicación.',
    'gateway.wifi.location.home': 'Casa',
    'gateway.wifi.location.office': 'Oficina',
    'gateway.wifi.location.factory': 'Fábrica',
    'gateway.wifi.location.shop': 'Tienda',
    'gateway.wifi.location.custom': 'Ubicación Personalizada',
    'gateway.wifi.location.custom.placeholder': 'Ingresa el nombre de la ubicación (ej. Mi Empresa)',
    'gateway.wifi.message': 'Ahora configuremos el nombre y contraseña de tu red WiFi.',
    'gateway.wifi.ssid.label': 'Nombre de Red (SSID)',
    'gateway.wifi.ssid.placeholder': 'Ingresa el nombre de la red',
    'gateway.wifi.ssid.suggestions': 'Sugerencias',
    'gateway.wifi.password.label': 'Contraseña WiFi',
    'gateway.wifi.password.placeholder': 'Ingresa contraseña (mín. 8 caracteres)',
    'gateway.wifi.password.weak': 'Débil',
    'gateway.wifi.password.medium': 'Media',
    'gateway.wifi.password.strong': 'Fuerte',
    'gateway.wifi.preview': 'Vista Previa de Red',

    'gateway.apply.title': 'Aplicando Configuración',
    'gateway.apply.message': 'Aplicando tu configuración WiFi al Gateway...',
    'gateway.apply.step1': 'Guardando configuración WiFi',
    'gateway.apply.step2': 'Reiniciando radio inalámbrico',
    'gateway.apply.step3': 'Cambiando a tu nueva red',
    'gateway.apply.step4': 'Finalizando configuración',
    'gateway.apply.success': '¡Configuración aplicada exitosamente!',
    'gateway.apply.switching': 'Cambiando de red...',
    'gateway.apply.switched': '¡Conectado a tu nueva red!',
    'gateway.apply.new.network': 'Tu nueva red WiFi está lista',

    // Extender Flow
    'extender.step1.title': 'Agregar Extensor',
    'extender.step1.message': 'Para agregar un extensor, escaneo los dispositivos cercanos a través de Bluetooth. Si tu Extensor soporta Bluetooth, enciéndelo y aparecerá en la lista a continuación. También puedes escanear el código QR en tu dispositivo o ingresar el número de serie manualmente.',
    'extender.step1.bluetooth.scanning': 'Escaneo Bluetooth',
    'extender.step1.bluetooth.searching': 'Buscando dispositivos cercanos...',
    'extender.step1.bluetooth.none': 'No se encontraron dispositivos cercanos',
    'extender.step1.bluetooth.rescan': 'Volver a escanear',
    'extender.step1.selected': 'Dispositivo seleccionado',
    'extender.step1.or': 'o usa otro método',
    'extender.step1.scan': 'Escanear Código QR',
    'extender.step1.manual': 'Ingresar Número de Serie',
    
    'extender.step2.title': 'Ingresar Número de Serie',
    'extender.step2.message': 'Por favor ingresa el número de serie que se encuentra en la parte posterior de tu extensor.',
    'extender.step2.placeholder': 'ej., EXT-1234-5678-90AB',
    'extender.step2.submit': 'Continuar',
    'extender.step2.invalid': 'Por favor ingresa un número de serie válido',
    
    'extender.step3.title': 'Autorizando Dispositivo',
    'extender.step3.message': 'Agregando extensor a tu red...',
    'extender.step3.registering': 'Registrando extensor...',
    'extender.step3.binding': 'Vinculando a ubicación...',
    'extender.step3.whitelisting': 'Actualizando lista blanca MAC...',
    'extender.step3.authorized': '¡Extensor autorizado!',
    
    'extender.room.title': 'Establecer Ubicación de Habitación',
    'extender.room.message': '¿En qué habitación se colocará este extensor?',
    'extender.room.main.location': 'Ubicación Principal',
    'extender.room.living': 'Sala de Estar',
    'extender.room.bedroom': 'Habitación',
    'extender.room.kitchen': 'Cocina',
    'extender.room.bathroom': 'Baño',
    'extender.room.study': 'Sala de Estudio',
    'extender.room.garage': 'Garaje',
    'extender.room.custom': 'Habitación Personalizada',
    'extender.room.custom.placeholder': 'Ingresa el nombre de la habitación',
    'extender.room.continue': 'Continuar',

    'extender.wifi.title': 'Configurar WiFi del Extensor',
    'extender.wifi.message': 'Configuremos la red WiFi para tu extensor.',

    'extender.poweron.title': 'Prepara tu Extensor',
    'extender.poweron.message': "¡Vamos a empezar! Por favor, sigue estos pasos para configurar tu extensor.",
    'extender.poweron.instruction1': 'Coloca el extensor en la ubicación deseada',
    'extender.poweron.instruction2': 'Conecta el adaptador de poder e insértalo',
    'extender.poweron.instruction3': 'Espera a que el LED se ponga sólido (aproximadamente 30-60 segundos)',
    'extender.poweron.confirm': 'El extensor está listo',
    
    'extender.step4.title': 'Enciende el Extensor',
    'extender.step4.message': 'Tu extensor ya está autorizado. Por favor enciéndelo para completar la configuración.',
    'extender.step4.instruction1': 'Coloca el extensor en la ubicación deseada',
    'extender.step4.instruction2': 'Enciende el extensor',
    'extender.step4.instruction3': 'Espera la conexión (puede tardar 1-2 minutos)',
    'extender.step4.ready': 'El extensor está encendido',
    
    'extender.step5.title': 'Conectando Extensor',
    'extender.step5.message': 'El extensor se está conectando a tu red...',
    'extender.step5.scanning': 'Buscando red de configuración...',
    'extender.step5.authenticating': 'Autenticando con Gateway...',
    'extender.step5.connecting': 'Conectando a la nube...',
    'extender.step5.finalizing': 'Aplicando configuración final...',
    
    'extender.success.title': '¡Extensor Conectado! 🎉',
    'extender.success.message': 'Tu extensor ya está en línea y extendiendo la cobertura de tu red.',
    'extender.success.device': 'Dispositivo',
    'extender.success.signal': 'Señal al Gateway',
    'extender.success.coverage': 'Área de Cobertura',
    'extender.success.add.another': 'Agregar Otro Extensor',
    'extender.success.finish': 'Finalizar Configuración',
    
    'extender.error.not.whitelisted': 'Conexión rechazada - dispositivo no autorizado',
    'extender.error.no.network': 'No se puede encontrar la red de configuración',
    'extender.error.timeout': 'Tiempo de espera agotado - por favor intenta de nuevo',
    
    // Device Detection (Legacy)
    'detect.searching': 'Genial! Estoy buscando tu router Wi-Fi...',
    'detect.found': '¡Perfecto! Encontré tu dispositivo:',
    'detect.confirm': '¿Es este tu router?',
    'detect.not.mine': 'Ese no es mío',
    'detect.correct': '¡Sí, es ese!',
    
    // Setup (Legacy)
    'setup.start': '¡Excelente! Déjame configurar tu red...',
    'setup.connecting': 'Conectando a tu router...',
    'setup.configuring': 'Optimizando configuración...',
    'setup.securing': 'Asegurando tu red...',
    'setup.finalizing': 'Finalizando...',
    
    // Success (Legacy)
    'success.title': '¡Todo listo! 🎉',
    'success.message': 'Tu red Gateway ahora está activa y optimizada. Puedes gestionar tu configuración en cualquier momento desde el panel.',
    'success.network.name': 'Nombre de Red',
    'success.devices': 'Dispositivos Conectados',
    'success.signal': 'Intensidad de Señal',
    'success.go.dashboard': 'Ir al Panel',
    
    // Error
    'error.title': '¡Ups! Algo salió mal',
    'error.connection': 'No pude conectar con el router. Esto podría deberse a:',
    'error.reason.power': 'El router no está encendido',
    'error.reason.distance': 'El dispositivo está muy lejos del router',
    'error.reason.network': 'Interferencia de red',
    'error.solutions': '¿Qué te gustaría hacer?',
    'error.retry.setup': 'Intentar de Nuevo',
    'error.manual.setup': 'Configuración Manual',
    'error.contact.support': 'Contactar Soporte',
    
    // Device Info
    'device.model': 'Modelo',
    'device.signal': 'Señal',
    'device.status': 'Estado',
    'device.status.online': 'En línea',
    'device.status.offline': 'Fuera de línea',
    
    // Accessibility
    'a11y.typing': 'El asistente está escribiין',
    'a11y.message.assistant': 'Mensaje del asistente',
    'a11y.message.user': 'Tu mensaje',
    'a11y.theme.toggle': 'Cambiar tema',
    'a11y.language.select': 'Seleccionar idioma',
    'a11y.progress': 'Progreso de configuración',
  },
  he: {
    // General
    'app.name': 'Gateway',
    'skip': 'דלג',
    'continue': 'המשך',
    'retry': 'נסה שוב',
    'done': 'סיום',
    'cancel': 'ביטול',
    'yes': 'כן',
    'no': 'לא',
    
    // Login
    'login.title': 'Heights',
    'login.subtitle': 'בחר איך אתה רוצה להתחבר',
    'login.method.title': 'בחר אسلوب התחברות',
    'login.method.local': 'התחבר עם מקומי',
    'login.method.local.description': 'התחבר ישירות לרשת המקומית שלך',
    'login.method.cloud': 'התחבר עם ענן',
    'login.method.cloud.description': 'גישה מרחוק באמצעות שירותים ענן',
    'login.form.title': 'פרטי התחברות',
    'login.form.username': 'שם משתמש',
    'login.form.email': 'כתובת אימייל',
    'login.form.password': 'סיסמה',
    'login.terms.agree': 'אני מסכים ל',
    'login.terms.link': 'תנאים והסכמים',
    'login.terms.required': 'עליך למסכים לתנאים כדי להמשיך',
    'login.error.method': 'אנא בחר אسلوب התחברות',
    'login.error.username': 'אנא הזן את שמך משתמש',
    'login.error.email': 'אנא הזן כתובת אימייל',
    'login.error.email.invalid': 'אנא הזן כתובת אימייל תקינה',
    'login.error.password': 'אנא הזן סיסמה',
    'login.error.password.short': 'הסיסמה חייבת להיות באורך של 6 תווים לפחות',
    'login.button': 'המשך',
    'login.footer': 'חיבור מאובטח • הגנה על הפרטיות',
    
    // Welcome
    'welcome.title': 'ברוכים הבאים ל-Heights!',
    'welcome.message': 'שלום! אני Janus, העוזר שלך ב-Heights. אעזור לך להגדיר את המכשירים שלך. מה תרצה להגדיר?',
    'welcome.setup.gateway': 'הגדר Gateway',
    'welcome.setup.extender': 'הוסף מרחיב טווח',
    'welcome.quick.setup': 'הגדרה מהירה',
    'welcome.quick.desc': 'כבר מכיר את התהליך? מלא פרטים ואנחנו נעשה הכל',

    // Quick Setup
    'quick.title': 'הגדרה מהירה',
    'quick.subtitle': 'מלא פרטים ואנחנו נטפל בשאר',
    'quick.form.location': 'מיקום',
    'quick.form.location.placeholder': 'למשל: בית, משרד, מפעל',
    'quick.form.ssid': 'שם רשת Wi-Fi (SSID)',
    'quick.form.ssid.placeholder': 'למשל: הבית-שלי-WiFi',
    'quick.form.password': 'סיסמת Wi-Fi',
    'quick.form.password.placeholder': 'מינימום 8 תווים',
    'quick.form.password.hint': 'לפחות 8 תווים. השתמש באותיות, מספרים וסמלים לסיסמה חזקה.',
    'quick.start': 'התחל הגדרה אוטומטית',
    'quick.running.start': 'מצוין! יש לי את כל מה שצריך. מתחיל הגדרה אוטומטית — אין צורך ללחוץ על כלום.',
    'quick.running.qr': 'קוד QR נסרק והמכשיר זוהה.',
    'quick.running.ocr': 'תווית המכשיר צולמה ופרטי הגישה נקראו.',
    'quick.running.wan': 'הגדרות WAN נשלחו ל-Gateway.',
    'quick.running.wifi': 'ה-Wi-Fi הוגדר כ-"{ssid}" וההגדרות הוחלו.',
    'quick.step.qr': 'סריקת קוד QR',
    'quick.step.ocr': 'צילום תווית מכשיר',
    'quick.step.wan': 'שליחת הגדרות WAN',
    'quick.step.wifi': 'התאמת Wi-Fi',
    'quick.step.apply': 'החלת הגדרות וחיבור',
    'quick.step.bt': 'סריקת Bluetooth',
    'quick.step.link': 'חיבור ל-Gateway',
    'quick.choose.title': 'מה תרצה להגדיר?',
    'quick.choose.gateway': 'Gateway',
    'quick.choose.gateway.desc': 'הגדרת מכשיר Gateway חדש',
    'quick.choose.extender': 'Extender',
    'quick.choose.extender.desc': 'הוספת Extender לרשת שלך',
    'quick.auto.label.location': 'מיקום',
    'quick.auto.label.ssid': 'שם רשת Wi-Fi',
    'quick.auto.label.password': 'סיסמה',
    'quick.auto.desc': 'נוצר אוטומטית — ניתן להתאים למטה',
    'quick.advanced': 'אפשרויות מתקדמות',
    'quick.advanced.hide': 'הסתר אפשרויות מתקדמות',
    'quick.running.bt': 'סריקת Bluetooth הושלמה — ה-Extender נמצא.',
    'quick.running.link': 'ה-Extender חובר ל-Gateway בהצלחה.',
    'quick.running.extender.wifi': 'הגדרות Wi-Fi נשלחו ל-Extender.',
    'quick.done.message.gateway': 'ה-Gateway שלך מוגדר ומוכן!',
    'quick.done.message.extender': 'ה-Extender שלך מוגדר ומוכן!',
    'quick.done.finish': 'סיום',
    'quick.done.repair': 'משהו השתבש — נסה שוב',
    'quick.done.repeat.extender': 'הוסף Extender נוסף',
    'quick.extender.select': 'בחר את ה-Gateway שלך',
    'quick.extender.nogateways': 'לא נמצאו Gateways. הגדר Gateway קודם.',
    'quick.extender.add.gateway': 'הוסף Gateway',
    'quick.extender.bt.tab': 'Bluetooth',
    'quick.extender.manual.tab': 'הזנה ידנית',
    'quick.extender.bt.scanning': 'מחפש Extenders בקרבת מקום…',
    'quick.extender.manual.serial.placeholder': 'מספר סידורי',
    'quick.extender.manual.model.placeholder': 'שם דגם',

    // Gateway Flow
    'gateway.step1.title': 'חבר את ה-Gateway שלך',
    'gateway.step1.message': 'אנא ודא שה-Gateway מופעל וכבל ה-Ethernet של WAN מחובר.',
    'gateway.step1.instruction1': 'הפעל את מכשיר ה-Gateway',
    'gateway.step1.instruction2': 'חבר כבל Ethernet WAN',
    'gateway.step1.instruction3': 'המתן עד שנורית ה-LED תהיה כחולה מלאה',
    'gateway.step1.ready': 'חיברתי אותו',
    
    // Gateway Onboarding - Location
    'gateway.location.title': 'קביעת מיקום',
    'gateway.location.message': 'איפה אתה מגדיר את ה-Gateway הזה?',
    'gateway.location.myhome.suffix': '\'s Home',
    'gateway.location.floor1': 'קומה 1',
    'gateway.location.floor2': 'קומה 2',
    'gateway.location.floor3': 'קומה 3',
    'gateway.location.custom': 'מיקום מותאם אישית',
    'gateway.location.custom.placeholder': 'הזן את שם המיקום',
    'gateway.location.continue': 'המשך',
    
    // Gateway WAN Configuration
    'gateway.wan.title': 'הגדרת WAN',
    'gateway.wan.message': 'كيف מתחבר ה-Gateway שלך לאינטרנט?',
    'gateway.wan.recommended': 'מומלץ',
    'gateway.wan.optional': 'אופציונלי',
    'gateway.wan.dhcp.title': 'DHCP (אוטומטי)',
    'gateway.wan.dhcp.desc': 'קבלת כתובת IP אוטומטית מהספק שלך',
    'gateway.wan.pppoe.title': 'PPPoE',
    'gateway.wan.pppoe.desc': 'התחבר באמצעות שם משתמש וסיסמה מהספק שלך',
    'gateway.wan.pppoe.howenter': 'איך תרצה להזין את פרטי ה-PPPoE שלך?',
    'gateway.wan.pppoe.scan': 'סרוק מסמך ISP',
    'gateway.wan.pppoe.scan.desc': 'השתמש במצלמה לקריאה אוטומטית של הפרטים ממכתב ה-ISP',
    'gateway.wan.pppoe.enter': 'הזן ידנית',
    'gateway.wan.pppoe.enter.desc': 'הקלד את שם המשתמש והסיסמה ל-PPPoE',
    'gateway.wan.pppoe.config': 'הגדרות PPPoE',
    'gateway.wan.pppoe.username': 'שם משתמש',
    'gateway.wan.pppoe.username.placeholder': 'הזן שם משתמש PPPoE',
    'gateway.wan.pppoe.password': 'סיסמה',
    'gateway.wan.pppoe.password.placeholder': 'הזן סיסמה PPPoE',
    'gateway.wan.static.title': 'IP סטטית',
    'gateway.wan.static.desc': 'הגדרות IP סטטיות ידניות',
    'gateway.wan.static.config': 'הגדרות IP סטטית',
    'gateway.wan.static.ip': 'כתובת IP',
    'gateway.wan.static.subnet': 'מסכתת תת-רשת',
    'gateway.wan.static.gateway': 'ゲטเวยי ברירת מחדל',
    'gateway.wan.static.dns1': 'DNS ראשי',
    'gateway.wan.static.dns2': 'DNS משני',
    
    // Gateway Selection for Extender
    'gateway.select.title': 'בחירת Gateway',
    'gateway.select.message': 'ל_gateway איזה אתה רוצה להוסיף את המרחיב?',
    'gateway.select.nogateways': 'לא נמצאו Gateways. עליך להגדיר Gateway ראשון לפני הוספת מרחיבים.',
    'gateway.select.required': 'Gateway נדרש',
    'gateway.select.required.desc': 'מרחיבים צריכים להתחבר ל-Gateway קיים. אנא הגדר את ה-Gateway שלך תחילה.',
    'gateway.select.setup.first': 'הגדר את ה-Gateway שלך כדי להתחיל',
    'gateway.select.add.another': 'הוסף Gateway נוסף',
    
    'gateway.step2.title': 'מתחבר לענן',
    'gateway.step2.message': 'ה-Gateway שלך מתחבר לענן...',
    'gateway.step2.registering': 'רשום מכשיר...',
    'gateway.step2.claiming': 'מקצה למיקום...',
    'gateway.step2.configuring': 'מגדי�� הגדרות...',
    'gateway.step2.starting': 'מפעיל רשת הגדרה...',
    
    'gateway.success.title': 'Gateway מקוון! 🎉',
    'gateway.success.message': 'ה-Gateway שלך כעת מקוון ומוכן. רשת ההגדרה פעילה להוספת מרחיבי טווח.',
    'gateway.success.ssid': 'SSID הגדרה',
    'gateway.success.status': 'מצב',
    'gateway.success.location': 'מיקום',
    'gateway.success.add.extender': 'הוסף מרחיב טווח',
    'gateway.success.finish': 'סיים הגדרה',

    // New Gateway Provisioning Flow
    'gateway.qr.title': 'סרוק קוד QR',
    'gateway.qr.message': 'אסרוק את קוד ה-QR של ה-Gateway כדי לקבל את פרטי ההגדרה שלו.',
    'gateway.qr.detected': 'קוד QR זוהה! קורא את פרטי המכשיר...',
    'gateway.qr.connecting': 'מתחבר לרשת ההגדרה של ה-Gateway שלך...',
    'gateway.qr.connected': 'מחובר! מאחזר תצורה...',
    'gateway.qr.connected.label': 'מחובר לרשת ההגדרה',
    'gateway.qr.connecting.label': 'מתחבר לרשת ההגדרה...',

    'gateway.ocr.title': 'לכידת פרטי ISP',
    'gateway.ocr.message': 'אני יכול לסרוק את מכתב הברוכים הבאים של ה-ISP שלך או תווית המודם כדי לקרוא אוטומטית את פרטי ה-PPPoE שלך.',
    'gateway.ocr.capture.button': 'סרוק מסמך',
    'gateway.ocr.capture.desc': 'כוון את המצלמה למכתב ה-ISP או לתווית המודם',
    'gateway.ocr.capture.start': 'התחל סריקה',
    'gateway.ocr.extracting': 'מחלץ פרטים מהתמונה...',
    'gateway.ocr.extracted': 'הפרטים חולצו בהצלחה!',
    'gateway.ocr.confirm': 'אשר פרטים',
    'gateway.ocr.review.title': 'בדוק פרטים שחולצו',
    'gateway.ocr.review.type': 'סוג חיבור',
    'gateway.ocr.review.username': 'שם משתמש',
    'gateway.ocr.review.password': 'סיסמה',
    'gateway.ocr.review.confirm': 'אשר והחל',
    'gateway.ocr.review.edit': 'ערוך',
    'gateway.ocr.edit.title': 'ערוך פרטים',
    'gateway.ocr.edit.save': 'שמור שינויים',
    'gateway.ocr.skip': 'הזן ידנית',
    'gateway.ocr.skip.desc': 'הקלד את הפרטים שלך ידנית במקום',

    'gateway.wanpush.title': 'שולח הגדרות WAN',
    'gateway.wanpush.message': 'שולח את הגדרות ה-WAN שלך ל-Gateway...',
    'gateway.wanpush.step1': 'מתחבר ל-Gateway',
    'gateway.wanpush.step2': 'שולח פרטי WAN',
    'gateway.wanpush.step3': 'מחיל הגדרות',
    'gateway.wanpush.step4': 'מאמת חיבור לאינטרנט',
    'gateway.wanpush.success': 'הגדרות WAN הוחלו בהצלחה!',
    'gateway.wanpush.internet.connected': 'מחובר לאינטרנט',
    'gateway.wanpush.internet.desc': 'ה-Gateway שלך מחובר כעת לאינטרנט',

    'gateway.wifi.title': 'התאם אישית את ה-WiFi שלך',
    'gateway.wifi.location.message': 'היכן אתה מגדיר את ה-Gateway הזה? זה עוזר לנו להציע את שם ה-WiFi הטוב ביותר עבור המיקום שלך.',
    'gateway.wifi.location.home': 'בית',
    'gateway.wifi.location.office': 'משרד',
    'gateway.wifi.location.factory': 'מפעל',
    'gateway.wifi.location.shop': 'חנות',
    'gateway.wifi.location.custom': 'מיקום מותאם אישית',
    'gateway.wifi.location.custom.placeholder': 'הזן שם מיקום (למשל: החברה שלי)',
    'gateway.wifi.message': 'עכשיו בוא נגדיר את שם רשת ה-WiFi והסיסמה שלך.',
    'gateway.wifi.ssid.label': 'שם רשת (SSID)',
    'gateway.wifi.ssid.placeholder': 'הזן שם רשת',
    'gateway.wifi.ssid.suggestions': 'הצעות',
    'gateway.wifi.password.label': 'סיסמת WiFi',
    'gateway.wifi.password.placeholder': 'הזן סיסמה (מינ. 8 תווים)',
    'gateway.wifi.password.weak': 'חלש',
    'gateway.wifi.password.medium': 'בינוני',
    'gateway.wifi.password.strong': 'חזק',
    'gateway.wifi.preview': 'תצוגה מקדימה של הרשת',

    'gateway.apply.title': 'מחיל הגדרות',
    'gateway.apply.message': 'מחיל את הגדרות ה-WiFi שלך ל-Gateway...',
    'gateway.apply.step1': 'שומר הגדרות WiFi',
    'gateway.apply.step2': 'מפעיל מחדש את הרדיו האלחוטי',
    'gateway.apply.step3': 'עובר לרשת החדשה שלך',
    'gateway.apply.step4': 'מסיים הגדרה',
    'gateway.apply.success': 'ההגדרות הוחלו בהצלחה!',
    'gateway.apply.switching': 'עובר רשתות...',
    'gateway.apply.switched': 'מחובר לרשת החדשה שלך!',
    'gateway.apply.new.network': 'רשת ה-WiFi החדשה שלך מוכנה',
    
    // Extender Flow
    'extender.step1.title': 'הוסף מרחיב טווח',
    'extender.step1.message': 'כדי להוסיף מרחיב טווח, אני סורק מכשירים קרובים דרך בלוטוס. אם המרחיב שלך תומך בלוטוס, הפעל אותו והוא יופיע ברשימה למטה. אתה גם יכול לסרוק את קוד ה-QR על המכשיר שלך או להזין את המספר הסידורי ידנית.',
    'extender.step1.bluetooth.scanning': 'סרוק בלוטוס',
    'extender.step1.bluetooth.searching': 'מחפש מכשירים קרובים...',
    'extender.step1.bluetooth.none': 'לא נמצאו מכשירים קרובים',
    'extender.step1.bluetooth.rescan': 'סרוק שוב',
    'extender.step1.selected': 'מכשיר נבחר',
    'extender.step1.or': 'או השתמש בשיטה אחרת',
    'extender.step1.scan': 'סרוק קוד QR',
    'extender.step1.manual': 'הזן מספר סידורי',
    
    'extender.step2.title': 'הזן מספר סידורי',
    'extender.step2.message': 'אנא הזן את המספר הסידורי שנמצא בגב של מרחיב הטווח שלך.',
    'extender.step2.placeholder': 'לדוגמה, EXT-1234-5678-90AB',
    'extender.step2.submit': 'המשך',
    'extender.step2.invalid': 'אנא הזן מספר סידורי תקין',
    
    'extender.step3.title': 'מאשר מכשיר',
    'extender.step3.message': 'מוסיף מרחיב טווח לרשת שלך...',
    'extender.step3.registering': 'רושם מרחיב טווח...',
    'extender.step3.binding': 'מחבר למיקום...',
    'extender.step3.whitelisting': 'מעדכן רשימה לבנה של MAC...',
    'extender.step3.authorized': 'מרחיב טווח מאושר!',
    
    'extender.room.title': 'קביעת מיקום חדר',
    'extender.room.message': 'באיזה חדר ימצא מרחיב הטווח הזה?',
    'extender.room.main.location': 'מיקום עיקרי',
    'extender.room.living': 'חדר מגורים',
    'extender.room.bedroom': 'חדר שינה',
    'extender.room.kitchen': 'מטבח',
    'extender.room.bathroom': 'אמבטיה',
    'extender.room.study': 'חדר עבודה',
    'extender.room.garage': 'מחסן',
    'extender.room.custom': 'חדר מותאם אישית',
    'extender.room.custom.placeholder': 'הזן את שם החדר',
    'extender.room.continue': 'המשך',

    'extender.wifi.title': 'הגדר WiFi למרחיב',
    'extender.wifi.message': 'בואו נגדיר את רשת ה-WiFi עבור המרחיב שלך.',

    'extender.poweron.title': 'הعد את המרחיב שלך',
    'extender.poweron.message': "בואו נתחיל! אנא עקוב אחר השלבים המבוקשים להגדיר את המרחיב שלך.",
    'extender.poweron.instruction1': 'הצב את המרחיב במקום המבוקש',
    'extender.poweron.instruction2': 'חבר את מתח המרחב ותנגן אותו',
    'extender.poweron.instruction3': 'המתן עד שנורית ה-LED תстанה כחולה (כ-30-60 שניות)',
    'extender.poweron.confirm': 'המרחיב שלך מוכן',
    
    'extender.step4.title': 'הפעל מרחיב טווח',
    'extender.step4.message': 'מרחיב הטווח שלך כעת מאושר. אנא הפעל אותו להשלמת ההגדרה.',
    'extender.step4.instruction1': 'מקם את מרחיב הטווח במיקום הרצוי',
    'extender.step4.instruction2': 'הפעל את מרחיב הטווח',
    'extender.step4.instruction3': 'המתן לחיבור (עשוי לקחת 1-2 דקות)',
    'extender.step4.ready': 'מרחיב הטווח מופעל',
    
    'extender.step5.title': 'מחבר מרחיב טווח',
    'extender.step5.message': 'מרחיב הטווח מתחבר לרשת שלך...',
    'extender.step5.scanning': 'סורק רשת הגדרה...',
    'extender.step5.authenticating': 'מאמת עם Gateway...',
    'extender.step5.connecting': 'מתחבר לענן...',
    'extender.step5.finalizing': 'מיישם תצורה סופית...',
    
    'extender.success.title': 'מרחיב טווח מחובר! 🎉',
    'extender.success.message': 'מרחיב הטווח שלך כעת מקוון ומרחיב את כיסוי הרשת שלך.',
    'extender.success.device': 'מכשיר',
    'extender.success.signal': 'אות ל-Gateway',
    'extender.success.coverage': 'אזור כיסוי',
    'extender.success.add.another': 'הוסף מרחיב טווח נוסף',
    'extender.success.finish': 'סיים הגדרה',
    
    'extender.error.not.whitelisted': 'חיבור נדחה - מכשיר לא מאושר',
    'extender.error.no.network': 'לא ניתן למצוא רשת הגדרה',
    'extender.error.timeout': 'תם זמן חיבור - אנא נסה שוב',
    
    // Device Detection (Legacy)
    'detect.searching': 'מעולה! אני סורק את הנתב שלך...',
    'detect.found': 'מצוין! מצאתי את המכשיר שלך:',
    'detect.confirm': 'האם זה הנתב שלך?',
    'detect.not.mine': 'זה לא שלי',
    'detect.correct': 'כן, זה הוא!',
    
    // Setup (Legacy)
    'setup.start': 'נהדר! תן לי להגדיר את הרשת שלך...',
    'setup.connecting': 'מתחבר לנתב שלך...',
    'setup.configuring': 'מייעל הגדרות...',
    'setup.securing': 'מאבטח את הרשת שלך...',
    'setup.finalizing': 'משלים...',
    
    // Success (Legacy)
    'success.title': 'הכל מוכן! 🎉',
    'success.message': 'רשת Gateway שלך פעילה ומאופטמלת. אתה יכול לנהל את ההגדרות שלך בכל עת מלוח הבקרה.',
    'success.network.name': 'שם רשת',
    'success.devices': 'מכשירים מחוברים',
    'success.signal': 'עוצמת אות',
    'success.go.dashboard': 'עבור ללוח בקרה',
    
    // Error
    'error.title': 'אופס! משהו השתבש',
    'error.connection': 'לא הצלחתי להתחבר לנתב. זה יכול להיות בגלל:',
    'error.reason.power': 'הנתב לא מופעל',
    'error.reason.distance': 'המכשיר רחוק מדי מהנתב',
    'error.reason.network': 'הפרעות רשת',
    'error.solutions': 'מה תרצה לעשות?',
    'error.retry.setup': 'נסה שוב',
    'error.manual.setup': 'התקנה ידנית',
    'error.contact.support': 'צור קשר עם תמיכה',
    
    // Device Info
    'device.model': 'דגם',
    'device.signal': 'אות',
    'device.status': 'מצב',
    'device.status.online': 'מחובר',
    'device.status.offline': 'לא מחובר',
    
    // Accessibility
    'a11y.typing': 'העוזר מקליד',
    'a11y.message.assistant': 'הודעת עוזר',
    'a11y.message.user': 'ההודעה שלך',
    'a11y.theme.toggle': 'החלף ערכת נושא',
    'a11y.language.select': 'בחר שפה',
    'a11y.progress': 'התקדמות התקנה',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('gateway-language');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'he';

  useEffect(() => {
    localStorage.setItem('gateway-language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}